### ISSUE TITLE
Player bug when stop music 

### ISSUE THREAD

**Issue by mikaelcandido** [Vinnih-1/MusicApp#5]
<h2>Description:</h2>When play music, and you stop the music with the button in the Footer, the icon in CardMusic continue show how "playning".
<br>
<h2>Steps for the replay the problem:</h2>
Play the music clicking in the CardMusic button, afeter click in stop in the Footer button.
<br><br>

![image](https://github.com/Vinnih-1/MusicApp/assets/58037508/5a50add5-2b40-47de-8e36-4840a2fd249e)

**Comment by Vinnih-1** [comment]
These buttons was changed by another button type
